### ISSUE TITLE
پشتیبانی از درگاه پاسارگاد

### ISSUE THREAD

**Issue by hesam-khorshidi** [alitnk/monopay#13]
پکیجتون خیلی عالی و کاربردیه
اگر پشتیبانی از درگاه بانک پاسارگاد رو هم اضافه کنید فوق العادس
ممنون

**Comment by alitnk** [comment]
خیلی ممنون.
من این روز‌ها سرم شلوغ هست متسفانه نمی‌رسم - اگه کسی بتونه PR درست کنه من مرج می‌کنم.

**Comment by Keivan-sf** [comment]
در حال پیاده سازی درایور پاسارگاد هستم. اگر ممکنه issue رو  assign کنید
