### ISSUE TITLE
What is `referenceId` in express example

### ISSUE THREAD

**Issue by Keivan-sf** [alitnk/monopay#18]
I was looking at [this](https://github.com/alitnk/monopay/blob/547f2ab4248a69f5b55795b3fa119a218d7245c4/examples/express-example/index.js#L76) line in express example. I'm wondering if this is just simply a typo mistake with `transactionId` or `BaseReceipt` might actually contain a property called `referenceId` in some case? Either way I was unable to transform this code into typescript because of the type error below:
```
Property 'referenceId' does not exist on type 'BaseReceipt<any>'.ts(2339)
```

**Comment by alitnk** [comment]
Yeah it's probably just `referenceId`... I might have changed it and just forgotten to update it. (not sure though, 😬)

**Comment by Keivan-sf** [comment]
Right then. I'll just change it to `transactionId`  for the example to be executable. Might as well pull a typescript implementation of it.
