### ISSUE TITLE
Add Pasargad driver to docs

### ISSUE THREAD

**Issue by alitnk** [alitnk/monopay#21]
- Check the "Implemented" and "Unit Tests" boxes for the driver in the docs - [Supported Drivers](https://github.com/alitnk/monopay/blob/documentation/src/components/drivers.mdx)
- Link the [PR description](https://github.com/alitnk/monopay/pull/20) next to the driver as a note for people to know it probably doesn't work on prod as it is right now

**Comment by alitnk** [comment]
Is it OK if I assign this one to you? @Keivan-sf

**Comment by Keivan-sf** [comment]
@alitnk  Sure, I was about to pull this one anyway
