### ISSUE TITLE
An unknown git error occurred

### ISSUE THREAD

**Issue by akbarazimifar** [alitnk/monopay#44]
npm install mobinco/monopay 
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/mobinco/monopay.git
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-08T14_03_18_128Z-debug-0.log
[root@server public_html]# cat /root/.npm/_logs/2022-11-08T14_03_18_128Z-debug-0.log

**Comment by alitnk** [comment]
این مشکل از فورکی که نصب کردید هست و به خود پکیج ربطی نداره. توی ریپو مربوطه باز کنید ایشو رو لطفا
