### ISSUE TITLE
description is required

### ISSUE THREAD

**Issue by everythinginjs** [alitnk/monopay#46]
Hey @alitnk  thanks the package, but in your example please add description since it has become required for zarinpal

```
const paymentInfo = await driver.requestPayment({
      amount: 20000,
      callbackUrl: process.env.APP_URL + "/callback",
      description: "Description about the transaction",
    });
```

[more info here](https://docs.zarinpal.com/paymentGateway/guide/#%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA)

**Comment by Keivan-sf** [comment]
If it is to be applied, we need to change the [api.ts](https://github.com/alitnk/monopay/blob/c0b45c40719fb7b9d2ccd169ba5fbff4445b26ec/src/drivers/zarinpal/api.ts#L22) as well

Current `RequestPaymentReq` interface:
https://github.com/alitnk/monopay/blob/c0b45c40719fb7b9d2ccd169ba5fbff4445b26ec/src/drivers/zarinpal/api.ts#L22-L57
