### ISSUE TITLE
خطای Next Js

### ISSUE THREAD

**Issue by chaveamin** [alitnk/monopay#61]
من هنگام درخواست پرداخت این خطارو دریافت میکنم: The top-level-await experiment is not enabled
کجا میتونم اینو فعال کنم؟

**Comment by alitnk** [comment]
از top-level await استفاده میکنید؟ یا پکیج ما داره این کار رو میکنه؟

**Comment by chaveamin** [comment]
خیر از top-level await استفاده نمیکنم. تو فایل `next.config.mjs` با `topLevelAwait: true` فعالش کردم ولی هنوز این اخطارو میده
اپ با Nextjs نوشته شده

**Comment by alitnk** [comment]
ما توی کدبیس پکیج شاید استفاده میکنیم ازش پس؟ اگه اینطوره میتونیم حذفش کنیم احتمالا.

**Comment by chaveamin** [comment]
این خطا در نکست نسخه 13 بود. الان که به آخرین نسخه(14) بروز کردم این حطارو میده
`Module not found: Can't resolve 'fs'`
![Screenshot 2024-01-07 105551](https://github.com/alitnk/monopay/assets/78597787/30f77a4e-a646-4ddd-a1ff-58722b564e1d)

**Comment by alitnk** [comment]
مونوپی برای سمت سرور هست. فقط باید توی کد سرور اجراش کنید. اینجور که بنظر میرسه توی صفحه تون دارید استفاده میکنید (pages/products/lagom.jsx)
